services:
  proxy:
    image: nginx:1.27-alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/public:ro
    depends_on:
      php:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    cap_drop: ["ALL"]
    cap_add: ["NET_BIND_SERVICE", "CHOWN", "SETGID", "SETUID"]

  php:
    build:
      context: ./docker/php
    working_dir: /var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: presence
      DB_USER: presence
      DB_PASSWORD: presence_pass
      COMPOSER_HOME: /tmp/composer
      COMPOSER_CACHE_DIR: /tmp/composer/cache
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - ./:/var/www/html
    read_only: true
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: presence
      MYSQL_USER: presence
      MYSQL_PASSWORD: presence_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot_pass --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: