services:
  apache:
    image: httpd:2.4
    ports:
      - "127.0.0.1:8080:80"          # bind to localhost for dev
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
      # - uploads_data:/var/www/html/public/uploads:ro   # serve uploads read-only here
    cap_drop: [ "ALL" ]
    cap_add: [ "SETUID", "SETGID" ]
    security_opt:
      - "no-new-privileges:true"
    command: ["httpd-foreground", "-c", "IncludeOptional conf/extra/httpd-vhosts.conf"]
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost/ || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - ./public:/var/www/html/public:ro
      - ./src:/var/www/html/src:ro
      - ./config.php:/var/www/html/config.php:ro
      # - uploads_data:/var/www/html/public/uploads:rw  # PHP writes here
    read_only: true
    tmpfs:
      - /tmp
    cap_drop: [ "ALL" ]
    cap_add: [ "SETUID", "SETGID" ]
    security_opt:
      - "no-new-privileges:true"
    healthcheck:
      test: [ "CMD-SHELL", "php -v >/dev/null" ]
      interval: 30s
      timeout: 5s
      retries: 5

# volumes:
#   uploads_data: