services:
  proxy:
    image: nginx:1.27-alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/public:ro
    # depends_on:
    #   php:
    #     condition: service_healthy
    security_opt:
      - no-new-privileges:true
    cap_drop: ["ALL"]
    cap_add: ["NET_BIND_SERVICE", "CHOWN", "SETGID", "SETUID"]

  php:
    build:
      context: ./docker/php
    working_dir: /var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      APP_BASE_URL: ${APP_BASE_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      COMPOSER_HOME: /tmp/composer
      COMPOSER_CACHE_DIR: /tmp/composer/cache
      COMPOSER_ALLOW_SUPERUSER: "1"
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_COOKIE_SECRET: ${AUTH0_COOKIE_SECRET}
      AUTH0_REDIRECT_URI: ${AUTH0_REDIRECT_URI}
      AUTH0_LOGOUT_REDIRECT_URI: ${AUTH0_LOGOUT_REDIRECT_URI}
      AUTH0_LOGIN_SUCCESS_REDIRECT_URI: ${AUTH0_LOGIN_SUCCESS_REDIRECT_URI}
    volumes:
      - ./:/var/www/html
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: